version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name kadai444 --s3-location s3://kadai444/artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src